apiVersion: v1 # Kubernetes API version
kind: Pod # Type of resource (Pod)
metadata: # Metadata about the Pod
  name: app1-pod-1 # Name of the Pod
  namespace: app1-dev # Namespace where the Pod will be created
  labels: # Labels for organizing resources
    app: app1 # Label for the application
    env: dev # Label for the environment (development)
spec: # Specification of the Pod's contents
  containers: # List of containers in the Pod
    - name: nginx # Name of the container
      image: nginx:latest # Docker image to use for the container
      ports: # Ports to expose from the container
        - containerPort: 80 # Expose port 80 for the container